#!/bin/sh

# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, find a compliant shell and set your PATH accordingly.
#
#   (2) You need the command `getopts` to be present in your system.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# Change from the installation directory to the directory where the script is located
cd "${app_path%/*}/.." || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonposix=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;;
  AIX* )            nonposix=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonposix" && [ "$MAX_FD" != "limited" ]
then
    MAX_FD=$( ulimit -n )
    if [ $? -eq 0 ]
    then
        if [ "$MAX_FD" -lt 32 ]
        then
            warn "WARNING: Could not query the maximum file descriptor limit: $MAX_FD"
        else
            # Set the command file descriptors for the Java process.
            # The alternative syntax "$JAVACMD" does not work in Zsh.
            eval exec -n \"$MAX_FD\" \"$JAVACMD\"
        fi
    else
        warn "WARNING: Could not query the maximum file descriptor limit: $MAX_FD"
    fi
fi

# For Darwin, add options to make locale settings work.
if "$darwin"
then
    export JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF-8"
fi

# For Cygwin or MSYS, switch paths to Windows format before running Java.
paths_switched=false
if "$cygwin" || "$msys"
then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                           # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}            # looks like a POSIX filepath
                    [ -e "$t" ] ;;                    #(
              *)    false ;;
            esac
        then
            # Switch arg to Windows format
            arg=$( cygpath --windows "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in `arg`.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
    paths_switched=true
fi

# Split up the JVM_OPTS And GRADLE_OPTS values into an array, following the shell
# quoting rules of https://stackoverflow.com/questions/56186154.
parse_opts() {
    local opts="$1"
    shift
    local safe=
    local accum=
    local literal=
    local quote=
    local split_opts=()
    local split_opt=
    local char=
    local chars=
    local remove_literal=
    local remove_quote=
    for split_opt in $opts ; do
        split_opts=( "${split_opts[@]}" "$split_opt" )
    done
    echo "${split_opts[@]}"
}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the Java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables
#   * The -Dorg.gradle.appname option
#   * The GCV and GCH environment variables
#   * The jar file and system properties to launch Gradle
#   * The remaining command arguments
eval set -- \
    $( parse_opts "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" ) \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"

# Check for the --daemon flag and launch in background if set.
if [ "$1" = "--daemon" ] ; then
    shift
    if "$darwin"
    then
        exec -b "$JAVACMD" "$@"
    else
        nohup "$JAVACMD" "$@" >/dev/null 2>&1 &
    fi
else
    exec "$JAVACMD" "$@"
fi